### ISSUE TITLE
Cannot find the Qed paper

### ISSUE THREAD

**Issue by gasche** [Frama-C/Qed#3]
I'm under lockdown at home and I can't access Springer paywalls. Is the Qed paper accessible somewhere? There is a [HAL submission](https://hal.archives-ouvertes.fr/cea-01809013) for it, but it does not contain the actual paper, only citation data.

**Comment by correnson** [comment]
I've just uploaded a PDF version of the paper on HAL website. Now waiting for validation...

**Comment by correnson** [comment]
The HAL entry has been successfully updated with the PDF 😏

**Comment by gasche** [comment]
Thanks a lot!

**Comment by correnson** [comment]
By the way, I realize that the paper is a bit outdated. Just to mention some recent additions to Qed since the original paper:
 - simplifiers for `a ? b : c` construction
 - linear sums, products and comparisons are now quotiented by GCD of coefficients
 - GCD-based simplifiers for divisions, remainders and their comparisons
 - more aggressive simplifications for (=>)
 - systematic packing of (a, not a) instead of using a cache (better perf. in practice)
 - new normalisation of quantifiers with so-called De-Brujin _levels_ for which no lifting is necessary in first-order logic fragment (contrary to _indices_ !)
 - efficient global substitution routines that nicely works with quantifiers

Those improvements can be found in the [src/plugins/qed](https://git.frama-c.com/pub/frama-c/-/tree/master/src/plugins/qed) directory of frama-c sources.
